
title : Mat - 調和的靈感
url: http://chchwy.github.com/

permalink: /posts/:title

markdown: redcarpet
pygments: false

auto: true
rdiscount:
  extensions: [smart]

production_url : http://chchwy.github.com
description: ""
disqus_shortname: chchwy
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : chchwy
  github : chchwy
  twitter : chchwy
