
name: 調和的靈感 Mat
url: http://chchwy.github.io

permalink: /:year/:month/:title.html

author: Matt Chiawen Chang
pygments: false

markdown: redcarpet

disqus_shortname: chchwy
analytics: UA-5266256-5

redcarpet:
  extensions: [tables, fenced_code_blocks]
