name: "調和的靈感 - Matt"
description: Blogging Like a Hacker.

baseurl: /
url: http://localhost:4000/
feed: /atom.xml

permalink: /:year/:month/:title.html
markdown: redcarpet

redcarpet:
  extensions: [tables]

lsi: true

pygments: false

