name: "調和的靈感 - Matt"
description: Blogging Like a Hacker.

baseurl: /
url: http://chchwy.github.com/
feed: /atom.xml

permalink: /:year/:month/:title.html
markdown: redcarpet

redcarpet:
  extensions: [tables, fenced_code_blocks]

lsi: true

pygments: false

